name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the code from GitHub repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Configure Git user
        run: |
          git config --global user.name "kpwai"
          git config --global user.email "khaingphyowai.mm@gmail.com"

      - name: Push to Hugging Face Space
        run: |
          # Setting the remote URL for Hugging Face Space
          git remote set-url origin https://huggingface.co/spaces/kpwai/Income-Prediction
          git push origin main  # Push changes to Hugging Face Space
